image: node:15-alpine
stages:
  - install
  - docker
  - build
  - deploy
  
install-dependencies:
  stage: install
  script:
    - apk update && apk add python make g++
    - apk add --update nodejs npm
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

build-docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  services:
  - docker:dind
  stage: docker
  environment: staging
  cache:
    paths:
      - node_modules/
  dependencies:
    - install-dependencies
  script:
    - echo "Build docker 🐳"
    - docker build . -t=legacy-blog-web:glb-${CI_PIPELINE_IID}
  artifacts:
    expire_in: 1hr
    paths:
      - build

build-app:
  stage: build
  environment: staging
  cache:
    paths:
      - node_modules/
  dependencies:
    - install-dependencies
    - build-docker
  script:
    - echo "Deploy a review app 🛠"
    - touch .env
    - echo "NODE_ENV=${NODE_ENV}" > .env
    - echo "REDUXBLOG_API_BASE_URL=${REDUXBLOG_API_BASE_URL}" >> .env
    - echo "REDUXBLOG_API_KEY=${REDUXBLOG_API_KEY}" >> .env
    - make build
  artifacts:
    expire_in: 1hr
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploy a review app 🚀"
    - mv dist/* public
  artifacts:
    paths:
      - public
  environment:
    name: staging
  only:
    - branches