apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-28T17:17:48Z"
  generation: 1
  labels:
    app: legacy-blog-web
  name: legacy-blog-web
  namespace: default
  resourceVersion: "35361"
  selfLink: /apis/apps/v1/namespaces/default/deployments/legacy-blog-web
  uid: fb7b148d-baf6-4023-9320-067fba70c5ea
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: legacy-blog-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacy-blog-web
    spec:
      containers:
      - image: caprilespe/legacy-blog-web:v1
        imagePullPolicy: IfNotPresent
        name: legacy-blog-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-28T17:18:38Z"
    lastUpdateTime: "2021-08-28T17:18:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-28T17:17:48Z"
    lastUpdateTime: "2021-08-28T17:18:38Z"
    message: ReplicaSet "legacy-blog-web-84f9fd97cc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
