apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-28T17:20:12Z"
  labels:
    app: legacy-blog-web
  name: legacy-blog-web
  namespace: default
  resourceVersion: "35397"
  selfLink: /api/v1/namespaces/default/services/legacy-blog-web
  uid: dd93aa74-7358-4f66-848b-8b2040533f52
spec:
  clusterIP: 10.103.16.113
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30731
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: legacy-blog-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
